/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ff14_auto_player_NativeMusicPlayer */

#ifndef _Included_ff14_auto_player_NativeMusicPlayer
#define _Included_ff14_auto_player_NativeMusicPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ff14_auto_player_NativeMusicPlayer
 * Method:    press
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_ff14_1auto_player_NativeMusicPlayer_press
  (JNIEnv *, jclass, jchar);

/*
 * Class:     ff14_auto_player_NativeMusicPlayer
 * Method:    release
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_ff14_1auto_player_NativeMusicPlayer_release
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif
