/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ff14_auto_util_WindowCheck */

#ifndef _Included_ff14_auto_util_WindowCheck
#define _Included_ff14_auto_util_WindowCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ff14_auto_util_WindowCheck
 * Method:    isFF14Window
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ff14_1auto_util_WindowCheck_isFF14Window
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
